//
// Created by Ярослав on 14.04.2023.
//

#ifndef NUMERICALINTEGRATIONMETHODS_CALCFUNCTIONAREA_H
#define NUMERICALINTEGRATIONMETHODS_CALCFUNCTIONAREA_H


class CalcFunctionArea {

};


#endif //NUMERICALINTEGRATIONMETHODS_CALCFUNCTIONAREA_H
